# Generated by Django 3.2.12 on 2022-05-11 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0004_auto_20220511_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergame',
            old_name='display_name',
            new_name='gammer_tag',
        ),
        migrations.RemoveField(
            model_name='usergame',
            name='display_image',
        ),
        migrations.RemoveField(
            model_name='userplatform',
            name='display_image',
        ),
        migrations.RemoveField(
            model_name='userplatform',
            name='display_name',
        ),
    ]
