# Generated by Django 3.2.12 on 2022-05-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0005_auto_20220511_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergame',
            name='display_image',
            field=models.ImageField(blank=True, default='call-of-duty.jpeg', null=True, upload_to='game_logos'),
        ),
    ]
