# Generated by Django 3.2.12 on 2022-05-12 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0006_usergame_display_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergame',
            name='user_id',
        ),
        migrations.AddField(
            model_name='usergame',
            name='userplatform_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='profile_app.userplatform'),
        ),
    ]
