# Generated by Django 3.2.12 on 2022-05-12 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0008_auto_20220512_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergame',
            name='userplatform_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='profile_app.userplatform'),
        ),
    ]
