# Generated by Django 3.2.12 on 2022-05-12 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile_app', '0009_alter_usergame_userplatform_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergame',
            name='userplatform_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profile_app.userplatform'),
        ),
        migrations.AlterField(
            model_name='userplatform',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
