# Generated by Django 3.2.12 on 2022-05-12 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_badgescategory_trophycategory'),
        ('profile_app', '0012_auto_20220512_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMatchParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_in_at', models.DateTimeField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.match')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.tournament')),
                ('usermatchparticipant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_app.usergame')),
            ],
        ),
    ]
