# Generated by Django 3.2.12 on 2022-05-06 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_completeprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='ext_report_status',
        ),
    ]
