# Generated by Django 3.2.12 on 2022-05-10 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_remove_completeprofile_igl_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompleteProfile',
        ),
    ]
