# Generated by Django 3.2.12 on 2022-05-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_delete_completeprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='display_image',
            field=models.ImageField(blank=True, default='call-of-duty.jpeg', null=True, upload_to='game_logos'),
        ),
    ]
